version: "3.8"

services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=posgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: