"""mirror many to many

Revision ID: c93f0b360d7b
Revises: fdc865baceb2
Create Date: 2023-02-16 13:03:44.560134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93f0b360d7b'
down_revision = 'fdc865baceb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers_books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('books_id', sa.INTEGER(), nullable=True),
    sa.Column('readers_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['books_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['readers_id'], ['readers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_books_reader_id', table_name='books')
    op.drop_constraint('books_reader_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'reader_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('reader_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('books_reader_id_fkey', 'books', 'readers', ['reader_id'], ['id'])
    op.create_index('ix_books_reader_id', 'books', ['reader_id'], unique=False)
    op.drop_table('readers_books')
    # ### end Alembic commands ###
